# general information
model_name: "test_dynamics_model"
model_type: "test_dynamics_model"
model_class: "test_dynamics_model"
extractor_class: "Not implemented"

extractor_config: "Not implemented"

# all vectors in FRD body frame if not specified otherwise

# the model configuration is used in the model you choose and can therefore vary in the amounts of topics.
# Generally it should have the following structure to interface with the standart rotor model and standart aerodynamics model:
model_config:
  actuators:
    rotors:
      # For example
      - rotor_0:
        description: "front right rotor" # for human readability
        dataframe_name: "u0" # column name in the dataframe, has to be contained in the dataframe name in required_ulog_topics or required_csv_topics
        rotor_axis:
          - 0
          - 0
          - -1
        turning_direction: -1
        position:
          - 0.35
          - 0.35
          - -0.07

    control_surfaces:
      # For example
      - control_surface_0:
        description: "aileron_right" # for human readability
        dataframe_name: "u1" # column name in the dataframe, has to be contained in the dataframe name in required_ulog_topics or required_csv_topics

  aerodynamics:
    stall_angle_deg: 20

# the data configuration is used in dynamics_model.py to load and arrange the data
dynamics_model_config:
  optimizer_config:
    optimizer_class: "LinearRegressor"
  estimate_forces: True
  estimate_moments: False
  use_sysid_maneuvers: False
  resample_freq: 100.0
  estimate_angular_acceleration: False
  data:
    required_ulog_topics:
      actuator_outputs:
        ulog_name:
          - "timestamp"
          - "output[0]"
          - "output[1]"
          - "output[2]"
          - "output[3]"
      vehicle_local_position:
        ulog_name:
          - "timestamp"
          - "ax"
          - "ay"
          - "az"
      vehicle_attitude:
        ulog_name:
          - "timestamp"
          - "q[0]"
          - "q[1]"
          - "q[2]"
          - "q[3]"
        dataframe_name:
          - "timestamp"
          - "q0"
          - "q1"
          - "q2"
          - "q3"
      sensor_combined:
        ulog_name:
          - "timestamp"
          - "accelerometer_m_s2[0]"
          - "accelerometer_m_s2[1]"
          - "accelerometer_m_s2[2]"
      manual_control_setpoint:
        ulog_name:
          - "timestamp"
          - "aux1"
          - "aux2"
          - "aux3"
          - "aux4"
          - "aux5"
          - "aux6"
        dataframe_name:
          - "timestamp"
          - "aux1"
          - "aux2"
          - "aux3"
          - "aux4"
          - "aux5"
          - "aux6"
      vehicle_land_detected:
        ulog_name:
          - "timestamp"
          - "landed"
        dataframe_name:
          - "timestamp"
          - "landed"
