# general information
model_name: "Gazebo Standard Plane"
model_type: "Standard Plane Longitudinal Model"
model_class: "FixedWingModel"
extractor_class: "FixedWingExtractorModel"

extractor_config:
  vmin: 8.0
  vmax: 20.0

  # all vectors in FRD body frame if not specified otherwise
model_config:
  mass: 1.45
  moment_of_inertia:
    Ixx: 0.107
    Iyy: 0.256
    Izz: 0.356
  actuators:
    rotors:
      # All rotors in the same group will share the coefficients
      puller_:
        - rotor:
          description: "puller rotor"
          rotor_type: "LinearRotorModel"
          dataframe_name: "throttle"

  aerodynamics:
    type: "LinearWingModel"
    area: 0.41
    chord: 0.19
    stall_angle_deg: 20
    sig_scale_factor: 30

dynamics_model_config:
  optimizer_config:
    optimizer_class: "LinearRegressor"
  estimate_forces: True
  estimate_moments: True
  resample_freq: 50.0
  estimate_angular_acceleration: False
  data:
    required_ulog_topics:
      actuator_outputs:
        id: 1
        ulog_name:
          - "timestamp"
          - "output[0]"
          - "output[1]"
          - "output[3]"
          - "output[4]"
          - "output[6]"
        dataframe_name:
          - "timestamp"
          - "u0"
          - "u1"
          - "u3"
          - "u4"
          - "u6"
        actuator_type:
          - "timestamp"
          - "control_surface"
          - "control_surface"
          - "control_surface"
          - "motor"
          - "control_surface"
      vehicle_local_position:
        ulog_name:
          - "timestamp"
          - "vx"
          - "vy"
          - "vz"
      vehicle_attitude:
        ulog_name:
          - "timestamp"
          - "q[0]"
          - "q[1]"
          - "q[2]"
          - "q[3]"
        dataframe_name:
          - "timestamp"
          - "q0"
          - "q1"
          - "q2"
          - "q3"
      vehicle_angular_velocity:
        ulog_name:
          - "timestamp"
          - "xyz[0]"
          - "xyz[1]"
          - "xyz[2]"
          - "xyz_derivative[0]"
          - "xyz_derivative[1]"
          - "xyz_derivative[2]"
        dataframe_name:
          - "timestamp"
          - "ang_vel_x"
          - "ang_vel_y"
          - "ang_vel_z"
          - "ang_acc_b_x"
          - "ang_acc_b_y"
          - "ang_acc_b_z"
      sensor_combined:
        ulog_name:
          - "timestamp"
          - "accelerometer_m_s2[0]"
          - "accelerometer_m_s2[1]"
          - "accelerometer_m_s2[2]"
        dataframe_name:
          - "timestamp"
          - "acc_b_x"
          - "acc_b_y"
          - "acc_b_z"
      manual_control_setpoint:
        ulog_name:
          - "timestamp"
          - "aux1"
          - "aux2"
          - "aux3"
          - "aux4"
          - "aux5"
          - "aux6"
        dataframe_name:
          - "timestamp"
          - "aux1"
          - "aux2"
          - "aux3"
          - "aux4"
          - "aux5"
          - "aux6"
      vehicle_thrust_setpoint:
        ulog_name:
          - "timestamp"
          - "xyz[0]"
        dataframe_name:
          - "timestamp"
          - "throttle"
      vehicle_torque_setpoint:
        ulog_name:
          - "timestamp"
          - "xyz[0]"
          - "xyz[1]"
          - "xyz[2]"
        dataframe_name:
          - "timestamp"
          - "aileron" # differential input to ailerons
          - "elevator" # elevator input
          - "rudder" # rudder input
      vehicle_land_detected:
        ulog_name:
          - "timestamp"
          - "landed"
        dataframe_name:
          - "timestamp"
          - "landed"