# general information
model_name: "Gazebo Standard Multirotor"
model_type: "Standard Multirotor"
model_class: "MultiRotorModel"

  # all vectors in FRD body frame if not specified otherwise
model_config:
  mass: 1.5
  moment_of_inertia:
    Ixx: 0.029125
    Iyy: 0.029125
    Izz: 0.055225
  actuators:
    rotors:
      vertical_:
        - rotor_0:
          description: "front right rotor"
          rotor_type: "RotorModel"
          dataframe_name: "u0"
          rotor_axis:
            - 0
            - 0
            - -1
          turning_direction: -1
          position:
            - 0.13
            - 0.22
            - -0.023

        - rotor_1:
          description: "back left rotor"
          rotor_type: "RotorModel"
          dataframe_name: "u1"
          rotor_axis:
            - 0
            - 0
            - -1
          turning_direction: -1
          position:
            - -0.13
            - -0.2
            - -0.023

        - rotor_2:
          description: "front left rotor"
          rotor_type: "RotorModel"
          dataframe_name: "u2"
          rotor_axis:
            - 0
            - 0
            - -1
          turning_direction: 1
          position:
            - 0.13
            - -0.2
            - -0.023

        - rotor_3:
          description: "back right rotor"
          rotor_type: "RotorModel"
          dataframe_name: "u3"
          rotor_axis:
            - 0
            - 0
            - -1
          turning_direction: 1
          position:
            - -0.13
            - 0.2
            - -0.023

dynamics_model_config:
  optimizer_config:
    optimizer_class: "QPOptimizer"
    optimzation_parameters:
    parameter_bounds:
      c_d_fuselage_x: !!python/tuple [0.0, 2.0]
      c_d_fuselage_y: !!python/tuple [0.0, 2.0]
      c_d_fuselage_z: !!python/tuple [0.0, 2.0]
      vertical_c_m_drag_z_lin: !!python/tuple [-1.0, 0.0]
      vertical_c_m_drag_z_quad: !!python/tuple [0.0, 2.0]
      vertical_c_m_leaver_lin: !!python/tuple [-1.0, 0.0]
      vertical_c_m_leaver_quad: !!python/tuple [0.0, 2.0]
      vertical_c_m_rolling: !!python/tuple [0.0, 2.0]
      vertical_rot_drag_lin: !!python/tuple [0.0, 2.0]
      vertical_rot_thrust_lin: !!python/tuple [-5.0, 0.0]
      vertical_rot_thrust_quad: !!python/tuple [0.0, 50.0]
  estimate_forces: True
  estimate_moments: True
  use_identification_ramps: False
  resample_freq: 250.0
  estimate_angular_acceleration: True
  data:
    required_ulog_topics:
      actuator_outputs:
        id: 0
        ulog_name:
          - "timestamp"
          - "output[0]"
          - "output[1]"
          - "output[2]"
          - "output[3]"
        dataframe_name:
          - "timestamp"
          - "u0"
          - "u1"
          - "u2"
          - "u3"
        actuator_type:
          - "timestamp"
          - "motor"
          - "motor"
          - "motor"
          - "motor"
      vehicle_local_position:
        ulog_name:
          - "timestamp"
          - "vx"
          - "vy"
          - "vz"
      vehicle_attitude:
        ulog_name:
          - "timestamp"
          - "q[0]"
          - "q[1]"
          - "q[2]"
          - "q[3]"
        dataframe_name:
          - "timestamp"
          - "q0"
          - "q1"
          - "q2"
          - "q3"
      vehicle_angular_velocity:
        ulog_name:
          - "timestamp"
          - "xyz[0]"
          - "xyz[1]"
          - "xyz[2]"
        dataframe_name:
          - "timestamp"
          - "ang_vel_x"
          - "ang_vel_y"
          - "ang_vel_z"
      sensor_combined:
        ulog_name:
          - "timestamp"
          - "accelerometer_m_s2[0]"
          - "accelerometer_m_s2[1]"
          - "accelerometer_m_s2[2]"
          - "gyro_rad[0]"
          - "gyro_rad[1]"
          - "gyro_rad[2]"
        dataframe_name:
          - "timestamp"
          - "acc_b_x"
          - "acc_b_y"
          - "acc_b_z"
          - "ang_acc_b_x"
          - "ang_acc_b_y"
          - "ang_acc_b_z"
