# general information
model_name: "Gazebo Standart VTOL"
model_type: "Standard VTOL"
model_class: "QuadPlaneModel"
extractor_class: "Not implemented"

extractor_config: "Not implemented"

  # all vectors in FRD body frame if not specified otherwise
model_config:
  mass: 5
  moment_of_inertia:
    Ixx: 0.477708333333
    Iyy: 0.341666666667
    Izz: 0.811041666667
  actuators:
    rotors:
      # All rotors in the same group will share the coefficients
      vertical_:
        - rotor_0:
          description: "front right rotor"
          dataframe_name: "u0"
          rotor_axis:
            - 0
            - 0
            - -1
          turning_direction: -1
          position:
            - 0.35
            - 0.35
            - -0.07

        - rotor_1:
          description: "back left rotor"
          dataframe_name: "u1"
          rotor_axis:
            - 0
            - 0
            - -1
          turning_direction: -1
          position:
            - -0.35
            - -0.35
            - -0.07

        - rotor_2:
          description: "front left rotor"
          dataframe_name: "u2"
          rotor_axis:
            - 0
            - 0
            - -1
          turning_direction: 1
          position:
            - 0.35
            - -0.35
            - -0.07

        - rotor_3:
          description: "back right rotor"
          dataframe_name: "u3"
          rotor_axis:
            - 0
            - 0
            - -1
          turning_direction: 1
          position:
            - -0.35
            - 0.35
            - -0.07
      puller_:
        - rotor_4:
          description: "puller rotor"
          dataframe_name: "u4"
          rotor_axis:
            - 1
            - 0
            - 0
          turning_direction: -1
          position:
            - 0.22
            - 0
            - 0

    control_surfaces:
      wing_:
        - control_surface_0:
          description: "aileron_right"
          dataframe_name: "u5"

        - control_surface_1:
          description: "aileron_left"
          dataframe_name: "u6"

        - control_surface_2:
          description: "elevator"
          dataframe_name: "u7"

  aerodynamics:
    area: 1.2
    stall_angle_deg: 20
    sig_scale_factor: 30

dynamics_model_config:
  optimizer_config:
    optimizer_class: "LinearRegressor"
  estimate_forces: True
  estimate_moments: True
  use_sysid_maneuvers: False
  resample_freq: 100.0
  estimate_angular_acceleration: False
  data:
    required_ulog_topics:
      actuator_outputs:
        ulog_name:
          - "timestamp"
          - "output[0]"
          - "output[1]"
          - "output[2]"
          - "output[3]"
          - "output[4]"
          - "output[5]"
          - "output[6]"
          - "output[7]"
        dataframe_name:
          - "timestamp"
          - "u0"
          - "u1"
          - "u2"
          - "u3"
          - "u4"
          - "u5"
          - "u6"
          - "u7"
        actuator_type:
          - "timestamp"
          - "motor"
          - "motor"
          - "motor"
          - "motor"
          - "motor"
          - "control_surface"
          - "control_surface"
          - "control_surface"
      vehicle_local_position:
        ulog_name:
          - "timestamp"
          - "vx"
          - "vy"
          - "vz"
      vehicle_attitude:
        ulog_name:
          - "timestamp"
          - "q[0]"
          - "q[1]"
          - "q[2]"
          - "q[3]"
        dataframe_name:
          - "timestamp"
          - "q0"
          - "q1"
          - "q2"
          - "q3"
      vehicle_angular_velocity:
        ulog_name:
          - "timestamp"
          - "xyz[0]"
          - "xyz[1]"
          - "xyz[2]"
        dataframe_name:
          - "timestamp"
          - "ang_vel_x"
          - "ang_vel_y"
          - "ang_vel_z"
      sensor_combined:
        ulog_name:
          - "timestamp"
          - "accelerometer_m_s2[0]"
          - "accelerometer_m_s2[1]"
          - "accelerometer_m_s2[2]"
          - "gyro_rad[0]"
          - "gyro_rad[1]"
          - "gyro_rad[2]"
        dataframe_name:
          - "timestamp"
          - "acc_b_x"
          - "acc_b_y"
          - "acc_b_z"
          - "ang_acc_b_x"
          - "ang_acc_b_y"
          - "ang_acc_b_z"
      manual_control_setpoint:
        ulog_name:
          - "timestamp"
          - "aux1"
          - "aux2"
          - "aux3"
          - "aux4"
          - "aux5"
          - "aux6"
        dataframe_name:
          - "timestamp"
          - "aux1"
          - "aux2"
          - "aux3"
          - "aux4"
          - "aux5"
          - "aux6"
      vehicle_land_detected:
        ulog_name:
          - "timestamp"
          - "landed"
        dataframe_name:
          - "timestamp"
          - "landed"
