# general information
model_name: "Gazebo Standard Plane"
model_type: "Standard Plane"
model_class:
  "StandardPlaneModel"

  # all vectors in FRD body frame if not specified otherwise
model_config:
  mass: 1.5
  moment_of_inertia:
    Ixx: 0.197563
    Iyy: 0.1458929
    Izz: 0.1477
  actuators:
    rotors:
      # All rotors in the same group will share the coefficients
      puller_:
        - rotor_4:
          description: "puller rotor"
          rotor_type: "RotorModel"
          dataframe_name: "u4"
          rotor_axis:
            - 1
            - 0
            - 0
          turning_direction: -1
          position:
            - 0.22
            - 0
            - 0

    control_surfaces:
      wing_:
        - control_surface_0:
          description: "aileron_right"
          dataframe_name: "u6"

        - control_surface_1:
          description: "aileron_left"
          dataframe_name: "u5"

        - control_surface_2:
          description: "elevator"
          dataframe_name: "u7"

        - control_surface_3:
          description: "rudder"
          dataframe_name: "u2"

        - control_surface_4:
          description: "flaps"
          dataframe_name: "u3"

  aerodynamics:
    area: 1.2
    stall_angle_deg: 20
    sig_scale_factor: 30

dynamics_model_config:
  optimizer_config:
    optimizer_class: "QPOptimizer"
    optimzation_parameters:
    parameter_bounds:
      c_d_wing_xz_fp_max: !!python/tuple [1.8, 1.8]
      c_d_wing_xz_fp_min: !!python/tuple [0.05, 0.05]
      c_d_wing_xz_lin: !!python/tuple [0, 100]
      c_d_wing_xz_offset: !!python/tuple [0, 0.5]
      c_d_wing_xz_quad: !!python/tuple [0, 100]
      c_l_wing_xz_fp: !!python/tuple [0.7, 0.7]
      c_l_wing_xz_lin: !!python/tuple [0, 5]
      c_l_wing_xz_offset: !!python/tuple [0, 0.5]
      c_m_x_wing_xz_lin: !!python/tuple [-1, 1]
      c_m_x_wing_xz_offset: !!python/tuple [-1, 1]
      control_surface_0_c_d_delta: !!python/tuple [-1000000, 1000000]
      control_surface_0_c_l_delta: !!python/tuple [-1000000, 1000000]
      control_surface_0_c_m_x_delta: !!python/tuple [-1000000, 1000000]
      control_surface_0_c_m_y_pitch_delta: !!python/tuple [-1000000, 1000000]
      control_surface_0_c_m_z_delta: !!python/tuple [-1000000, 1000000]
      control_surface_1_c_d_delta: !!python/tuple [-1000000, 1000000]
      control_surface_1_c_l_delta: !!python/tuple [-1000000, 1000000]
      control_surface_1_c_m_x_delta: !!python/tuple [-1000000, 1000000]
      control_surface_1_c_m_y_pitch_delta: !!python/tuple [-1000000, 1000000]
      control_surface_1_c_m_z_delta: !!python/tuple [-1000000, 1000000]
      control_surface_2_c_d_delta: !!python/tuple [-1000000, 1000000]
      control_surface_2_c_l_delta: !!python/tuple [-1000000, 1000000]
      control_surface_2_c_m_x_delta: !!python/tuple [-1000000, 1000000]
      control_surface_2_c_m_y_pitch_delta: !!python/tuple [-1000000, 1000000]
      control_surface_2_c_m_z_delta: !!python/tuple [-1000000, 1000000]
      control_surface_3_c_d_delta: !!python/tuple [-1000000, 1000000]
      control_surface_3_c_l_delta: !!python/tuple [-1000000, 1000000]
      control_surface_3_c_m_x_delta: !!python/tuple [-1000000, 1000000]
      control_surface_3_c_m_y_pitch_delta: !!python/tuple [-1000000, 1000000]
      control_surface_3_c_m_z_delta: !!python/tuple [-1000000, 1000000]
      control_surface_4_c_d_delta: !!python/tuple [-1000000, 1000000]
      control_surface_4_c_l_delta: !!python/tuple [-1000000, 1000000]
      control_surface_4_c_m_x_delta: !!python/tuple [-1000000, 1000000]
      control_surface_4_c_m_y_pitch_delta: !!python/tuple [-1000000, 1000000]
      control_surface_4_c_m_z_delta: !!python/tuple [-1000000, 1000000]
      puller_c_m_drag_z_lin: !!python/tuple [-1000000, 1000000]
      puller_c_m_drag_z_quad: !!python/tuple [-1000000, 1000000]
      puller_c_m_leaver_lin: !!python/tuple [0, 0]
      puller_c_m_leaver_quad: !!python/tuple [0, 0]
      puller_c_m_rolling: !!python/tuple [0, 0]
      puller_rot_drag_lin: !!python/tuple [0, 10]
      puller_rot_thrust_lin: !!python/tuple [-1, 0]
      puller_rot_thrust_quad: !!python/tuple [0, 20]
  estimate_forces: True
  estimate_moments: True
  resample_freq: 50.0
  data:
    required_ulog_topics:
      actuator_outputs:
        ulog_name:
          - "timestamp"
          - "output[2]" # Rudder
          - "output[3]" # Flaps
          - "output[4]" # motor
          - "output[5]" # left aileron
          - "output[6]" # right aileron
          - "output[7]" # elevator
        dataframe_name:
          - "timestamp"
          - "u2"
          - "u3"
          - "u4"
          - "u5"
          - "u6"
          - "u7"
        actuator_type:
          - "timestamp"
          - "control_surface"
          - "control_surface"
          - "motor"
          - "control_surface"
          - "control_surface"
          - "control_surface"
      vehicle_local_position:
        ulog_name:
          - "timestamp"
          - "vx"
          - "vy"
          - "vz"
      vehicle_attitude:
        ulog_name:
          - "timestamp"
          - "q[0]"
          - "q[1]"
          - "q[2]"
          - "q[3]"
        dataframe_name:
          - "timestamp"
          - "q0"
          - "q1"
          - "q2"
          - "q3"
      vehicle_angular_velocity:
        ulog_name:
          - "timestamp"
          - "xyz[0]"
          - "xyz[1]"
          - "xyz[2]"
        dataframe_name:
          - "timestamp"
          - "ang_vel_x"
          - "ang_vel_y"
          - "ang_vel_z"
      sensor_combined:
        ulog_name:
          - "timestamp"
          - "accelerometer_m_s2[0]"
          - "accelerometer_m_s2[1]"
          - "accelerometer_m_s2[2]"
        dataframe_name:
          - "timestamp"
          - "acc_b_x"
          - "acc_b_y"
          - "acc_b_z"
      vehicle_angular_acceleration:
        ulog_name:
          - "timestamp"
          - "xyz[0]"
          - "xyz[1]"
          - "xyz[2]"
        dataframe_name:
          - "timestamp"
          - "ang_acc_b_x"
          - "ang_acc_b_y"
          - "ang_acc_b_z"
