---
# general information
model_name: "Gazebo Delta VTOL"
model_type: "Delta VTOL"
model_file:
  "delta_quad_plane_model.py"

  # all vectors in FRD body frame if not specified otherwise
model_config:
  actuators:
    rotors:
      # All rotors in the same group will share the coefficients
      vertical_:
        - rotor_0:
          description: "front right rotor"
          dataframe_name: "u0"
          rotor_axis:
            - 0
            - 0
            - -1
          turning_direction: -1
          position:
            - 0.35
            - 0.35
            - -0.07

        - rotor_1:
          description: "back left rotor"
          dataframe_name: "u1"
          rotor_axis:
            - 0
            - 0
            - -1
          turning_direction: -1
          position:
            - -0.35
            - -0.35
            - -0.07

        - rotor_2:
          description: "front left rotor"
          dataframe_name: "u2"
          rotor_axis:
            - 0
            - 0
            - -1
          turning_direction: 1
          position:
            - 0.35
            - -0.35
            - -0.07

        - rotor_3:
          description: "back right rotor"
          dataframe_name: "u3"
          rotor_axis:
            - 0
            - 0
            - -1
          turning_direction: 1
          position:
            - -0.35
            - 0.35
            - -0.07
      puller_:
        - rotor_4:
          description: "puller rotor"
          dataframe_name: "u4"
          rotor_axis:
            - 1
            - 0
            - 0
          turning_direction: -1
          position:
            - 0.22
            - 0
            - 0

    control_surfaces:
      - control_surface_0:
        description: "ailevon_right"
        dataframe_name: "u5"

      - control_surface_1:
        description: "ailevon_left"
        dataframe_name: "u6"

  aerodynamics:
    stall_angle_deg: 20
    sig_scale_factor: 30

dynamics_model_config:
  estimate_forces: True
  estimate_moments: False
  resample_freq: 5.0
  data:
    required_ulog_topics:
      actuator_outputs:
        ulog_name:
          - "timestamp"
          - "output[0]"
          - "output[1]"
          - "output[2]"
          - "output[3]"
          - "output[4]"
          - "output[5]"
          - "output[6]"
        dataframe_name:
          - "timestamp"
          - "u0"
          - "u1"
          - "u2"
          - "u3"
          - "u5"
          - "u6"
          - "u4"
        actuator_type:
          - "timestamp"
          - "motor"
          - "motor"
          - "motor"
          - "motor"
          - "control_surcafe"
          - "control_surcafe"
          - "motor"
      vehicle_local_position:
        ulog_name:
          - "timestamp"
          - "vx"
          - "vy"
          - "vz"
      vehicle_attitude:
        ulog_name:
          - "timestamp"
          - "q[0]"
          - "q[1]"
          - "q[2]"
          - "q[3]"
        dataframe_name:
          - "timestamp"
          - "q0"
          - "q1"
          - "q2"
          - "q3"
      sensor_combined:
        ulog_name:
          - "timestamp"
          - "accelerometer_m_s2[0]"
          - "accelerometer_m_s2[1]"
          - "accelerometer_m_s2[2]"
