---
# general information
model_name: "Gazebo Standart VTOL"
model_type: "Standard VTOL"
model_file:
  "quad_plane_model.py"

  # all vectors in FRD body frame if not specified otherwise
model_configuration:
  actuators:
    n_actuators: 8
    n_rotors: 5
    n_control_surfaces: 3
    rotors:
      - rotor_0:
        description: "front right rotor"
        dataframe_name: "u0"
        force_direction:
          - 0
          - 0
          - -1
        turning_direction: -1
        position:
          - 0.35
          - 0.35
          - -0.07

      - rotor_1:
        description: "back left rotor"
        dataframe_name: "u1"
        force_direction:
          - 0
          - 0
          - -1
        turning_direction: -1
        position:
          - -0.35
          - -0.35
          - -0.07

      - rotor_2:
        description: "front left rotor"
        dataframe_name: "u2"
        force_direction:
          - 0
          - 0
          - -1
        turning_direction: 1
        position: 0.35
          - -0.35
          - - 0.07

      - rotor_3:
        description: "back right rotor"
        dataframe_name: "u3"
        force_direction:
          - 0
          - 0
          - -1
        turning_direction: 1
        position:
          - -0.35
          - 0.35
          - - 0.07

      - rotor_4:
        description: "puller rotor"
        dataframe_name: "u4"
        force_direction:
          - 1
          - 0
          - 0
        turning_direction: -1
        position:
          - 0.22
          - 0
          - 0

    control_surfaces:
      - control_surface_0:
        description: "aileron_right"
        dataframe_name: "u5"

      - control_surface_1:
        description: "aileron_left"
        dataframe_name: "u6"

      - control_surface_2:
        description: "elevator"
        dataframe_name: "u7"

  aerodynamics:
    stall_angle_deg: 20

data:
  load_from_csv: False
  load_from_ulog: True
  required_ulog_topics:
    actuator_outputs:
      ulog_name:
        - "timestamp"
        - "output[0]"
        - "output[1]"
        - "output[2]"
        - "output[3]"
        - "output[4]"
        - "output[5]"
        - "output[6]"
        - "output[7]"
      dataframe_name:
        - "timestamp"
        - "u0"
        - "u1"
        - "u2"
        - "u3"
        - "u4"
        - "u5"
        - "u6"
        - "u7"
    vehicle_local_position:
      ulog_name:
        - "timestamp"
        - "vx"
        - "vy"
        - "vz"
    vehicle_attitude:
      ulog_name:
        - "timestamp"
        - "q[0]"
        - "q[1]"
        - "q[2]"
        - "q[3]"
      dataframe_name:
        - "timestamp"
        - "q0"
        - "q1"
        - "q2"
        - "q3"
    vehicle_angular_velocity:
      ulog_name:
        - "timestamp"
        - "xyz[0]"
        - "xyz[1]"
        - "xyz[2]"
      dataframe_name:
        - "timestamp"
        - "ang_vel_x"
        - "ang_vel_y"
        - "ang_vel_z"
    sensor_combined:
      ulog_name:
        - "accelerometer_m_s2[0]"
        - "accelerometer_m_s2[1]"
        - "accelerometer_m_s2[2]"
    vehicle_angular_acceleration:
      ulog_name:
        - "timestamp"
        - "xyz[0]"
        - "xyz[1]"
        - "xyz[2]"
      dataframe_name:
        - "timestamp"
        - "ang_acc_x"
        - "ang_acc_y"
        - "ang_acc_z"
